name: Convert README to HTML

on:
  push:
    branches: [main]
    paths:
      - "README.md"

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install -g marked

      - name: Convert README to HTML
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Project Documentation</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                      line-height: 1.6;
                      max-width: 900px;
                      margin: 0 auto;
                      padding: 20px;
                      color: #24292e;
                  }
                  a {
                      color: #0366d6;
                      text-decoration: none;
                  }
                  a:hover {
                      text-decoration: underline;
                  }
                  pre {
                      background-color: #f6f8fa;
                      border-radius: 3px;
                      padding: 16px;
                      overflow: auto;
                  }
                  code {
                      background-color: #f6f8fa;
                      border-radius: 3px;
                      padding: 0.2em 0.4em;
                      font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace;
                  }
                  img {
                      max-width: 100%;
                  }
                  h1, h2, h3, h4, h5, h6 {
                      margin-top: 24px;
                      margin-bottom: 16px;
                      font-weight: 600;
                      line-height: 1.25;
                  }
                  h1 {
                      padding-bottom: 0.3em;
                      font-size: 2em;
                      border-bottom: 1px solid #eaecef;
                  }
                  h2 {
                      padding-bottom: 0.3em;
                      font-size: 1.5em;
                      border-bottom: 1px solid #eaecef;
                  }
                  blockquote {
                      padding: 0 1em;
                      color: #6a737d;
                      border-left: 0.25em solid #dfe2e5;
                      margin: 0;
                  }
                  table {
                      border-collapse: collapse;
                      width: 100%;
                      margin-bottom: 16px;
                  }
                  table th, table td {
                      padding: 6px 13px;
                      border: 1px solid #dfe2e5;
                  }
                  table tr {
                      background-color: #fff;
                      border-top: 1px solid #c6cbd1;
                  }
                  table tr:nth-child(2n) {
                      background-color: #f6f8fa;
                  }
              </style>
          </head>
          <body>
              <div id="content"></div>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/4.0.2/marked.min.js"></script>
              <script>
                  fetch("README.md")
                      .then(response => response.text())
                      .then(markdown => {
                          document.getElementById("content").innerHTML = marked.parse(markdown);
                      })
                      .catch(error => {
                          console.error("Error fetching README:", error);
                          document.getElementById("content").innerHTML = "<h1>Error loading content</h1><p>Could not load README.md file.</p>";
                      });
              </script>
          </body>
          </html>' > index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate index.html from README.md"
          git push
